CREATE TABLE IF NOT EXISTS users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT,
    title VARCHAR (255) NOT NULL UNIQUE,
    description VARCHAR (200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    rating INTEGER NOT NULL,
    user_like INTEGER NOT NULL
);

CREATE TABLE IF EXISTS genres (
    id INTEGER GENERATED BY DEFAULT,
    title VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id int REFERENCES films (id),
    genre_id int REFERENCES genres (id),
    PRIMARY KEY (film_id, genre_id)
);