-- ВЫПУСКАЙТЕ КРЯКЕНА (если что-то сломалось очисти это что-то)

DROP TABLE IF EXISTS film_like;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS mpa;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    login VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(20) UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name VARCHAR(100) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    genre INTEGER,
    user_like INTEGER,
    mpa INTEGER REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(65) UNIQUE
);

CREATE TABLE IF NOT EXISTS film_like (
        film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
        user_like INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
        PRIMARY KEY (film_id, user_like)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE ON UPDATE CASCADE,
    genre_id INTEGER REFERENCES genres (genre_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT validate_request CHECK (user_id <> friend_id)
);